# Generated by Django 5.2.5 on 2025-08-27 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.CharField(default='Confirmed', max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('passengers', models.ManyToManyField(to='travels.passengerdetails')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.traveloptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='travels_boo_user_id_0cccdf_idx'), models.Index(fields=['trip'], name='travels_boo_trip_id_37decc_idx'), models.Index(fields=['booking_status'], name='travels_boo_booking_fc1719_idx')],
            },
        ),
    ]
