# Generated by Django 5.2.5 on 2025-08-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_bookingtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtrip',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
