# Generated by Django 5.2.5 on 2025-08-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_bookingtrip_seat_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdetails',
            name='adhar_number',
            field=models.CharField(max_length=12),
        ),
    ]
