# .github/workflows/django-ci.yml

name: Django CI

on:
  push:
    branches: [ "main" ] # Runs on pushes to main and develop branches
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch

# What jobs to run
jobs:
  test:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      # Install dependencies
      - name.env: Install Dependencies
        env:
          PSYCOPG2_BINARY: "true" 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  

      #  Run Tests with Coverage
      - name: Run Tests with Coverage
        run: |
          coverage run manage.py test
          coverage report
